version: '3.5'
services:
    web:
        build: .
        container_name: hospital-demo
        command: npm run dev  
        image: node:alpine3.15 
        ports:
            - "3000:80"
        volumes:
            - .:/opt/app
            - /opt/app/node_modules/
        networks:
            - demo-network
        # environment:
        #     - NODE_ENV=local
networks:
    demo-network:
        name: demo-network